[package]
name = "smartagents-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.5.0", features = ["build"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
